[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["Aperture OS Team"]

[dependencies]
spin = "0.10.0"
limine = "0.6.5"
pe-parser = { path = "../crates/pe-parser" }
x86-decode = { path = "../crates/x86-decode" }
aarch64-decode = { path = "../crates/aarch64-decode" }

[dependencies.x86_64]
version = "0.15.5"
optional = true

[dependencies.uart_16550]
version = "0.3.2"
optional = true

[features]
default = ["arch_x86_64"]
arch_x86_64 = ["dep:x86_64", "dep:uart_16550"]
arch_aarch64 = []
